config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index, :new, :create] do
    member do
      patch :lend
      patch :return
    end
  end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'books#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  belongs_to :borrower, class_name: 'User'

  validates :title, presence: true
  validates :author, presence: true

  delegate :full_name, to: :borrower, prefix: true, allow_nil: true
  delegate :full_name, to: :owner, prefix: true, allow_nil: true

  scope :lent_books, -> { where.not(borrower: nil) }

  def lend(user)
    return if owner.id == user.id
    return if lent?
    self.borrower = user
    save
  end

  def return
    self.borrower = nil
    save
  end

  def lent?
    borrower.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_books,
           class_name: 'Book',
           foreign_key: 'owner_id',
           dependent: :destroy

  has_many :borrowed_books,
           class_name: 'Book',
           foreign_key: 'borrower_id',
           dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true

  delegate :lent_books, to: :owned_books

  scope :without, ->(user) { where.not(id: user) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end

  private

  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  def index
    @owned_books    = current_user.owned_books.order(:title)
    @lent_books     = current_user.lent_books.order(:title)
    @borrowed_books = current_user.borrowed_books.order(:title)
    @users          = User.without(current_user).order(:first_name)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # POST /books
  def create
    @book = current_user.owned_books.build(new_book_params)

    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH /books/1/lend
  def lend
    @book     = current_user.owned_books.find(params[:id])
    @borrower = User.find(lend_book_params[:borrower_id])

    @book.lend(@borrower)

    redirect_to books_path, notice: 'Book was successfully lent.'
  end

  # PATCH /books/1/return
  def return
    @book = current_user.borrowed_books.find(params[:id])

    @book.return

    redirect_to books_path, notice: 'Book was successfully returned.'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def new_book_params
    params.require(:book).permit(:title, :author)
  end

  def lend_book_params
    params.require(:book).permit(:borrower_id)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_borrowed_books.html.erb
<h2>Borrowed Books</h2>
<table class='table table-striped'>
  <thead>
    <tr>
      <th class='col-md-3'><%= Book.human_attribute_name(:title) %></th>
      <th class='col-md-3'><%= Book.human_attribute_name(:author) %></th>
      <th class='col-md-3'><%= Book.human_attribute_name(:owner) %></th>
      <th class='col-md-3'><%= t '.actions', default: t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.owner_full_name %></td>
        <td>
          <%= form_for book, url: return_book_path(book),
                             method: :patch,
                             html: { class: 'form-horizontal form-model' } do |f| %>

            <%= f.submit 'Return', class: 'btn btn-xs btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_lent_books.html.erb
<h2>Lent Books</h2>
<table class='table table-striped'>
  <thead>
    <tr>
      <th class='col-md-3'><%= Book.human_attribute_name(:title) %></th>
      <th class='col-md-3'><%= Book.human_attribute_name(:author) %></th>
      <th class='col-md-6'><%= Book.human_attribute_name(:borrower) %></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.borrower_full_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_owned_books.html.erb
<h2>Owned Books</h2>
<table class='table table-striped'>
  <thead>
    <tr>
      <th class='col-md-3'><%= Book.human_attribute_name(:title) %></th>
      <th class='col-md-6'><%= Book.human_attribute_name(:author) %></th>
      <th class='col-md-3'><%= t '.actions', default: t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td>
          <% unless book.lent? %>
            <%= form_for book, url: lend_book_path(book),
                               method: :patch,
                               html: { class: 'form-horizontal form-model' } do |f| %>

              <%= f.submit 'Lend', class: 'btn btn-xs btn-primary' %>

              <%= f.collection_select :borrower_id,
                                      users,
                                      :id,
                                      :full_name %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<div class='page-header'>
  <h1>Books</h1>
</div>

<%= render partial: 'owned_books', locals: { books: @owned_books, users: @users } %>
<%= render partial: 'lent_books', locals: { books: @lent_books } %>
<%= render partial: 'borrowed_books', locals: { books: @borrowed_books } %>

<%= link_to t('.new', default: t('helpers.links.new')),
            new_book_path,
            class: 'btn btn-primary' %>

app/views/books/new.html.erb
<div class='page-header'>
  <h1>New Book</h1>
</div>

<%= form_for @book, html: { class: 'form-horizontal form-model' } do |f| %>
  <% if @book.errors.any? %>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class='form-group'>
    <%= f.label :title, class: 'control-label col-md-2' %>
    <div class='col-md-10'>
      <%= f.text_field :title, class: 'text-field form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :author, class: 'control-label col-md-2' %>
    <div class='col-md-10'>
      <%= f.text_field :author, class: 'text-field form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t('helpers.links.cancel')),
                  books_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Anatec's Library", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anatec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
  <header>
    <%= render partial: "elements/navbar" %>
  </header>

  <main class="yield">
    <%= bootstrap_flash %>
    <%= yield %>
  </main>
</body>
</html>